import numpy as np

CUDA = True
CHECK_POINT = 0
MAX_EPOCH = 200

BATCH_SIZE = 1024
STDDEV=0.01
LR = 1e-5
DECAY = 0

NAME='test1' # For save figure name
OUTPUT_DIRECTORY = './output'
DATASET_PICKLE_FILE = '{0}/dataset.pickle'.format(OUTPUT_DIRECTORY)
CSV_DATA_FILE = 'NHIS_OPEN_GJ_2017.csv'

ATTR_FEATURE_ARRAY = np.arange(5, 27) # 신장 ~ 음주여부
ATTR_FEATURE_ARRAY = np.concatenate((ATTR_FEATURE_ARRAY, 32), axis=None) # 치석포함
AGE_INPUT_LAYER_SIZE = ATTR_FEATURE_ARRAY.shape[0]
AGE_OUTPUT_LAYER_SIZE = 1

GENDER_INPUT_LAYER_SIZE = AGE_INPUT_LAYER_SIZE
GENDER_OUTPUT_LAYER_SIZE = 2 # 2-d class

# 0은 기준년도
ATTR_SERIAL_IDX = 1
ATTR_GENDER_IDX = 2
ATTR_AGE_IDX = 3
ATTR_TARTAR_IDX = 32 # 32 -> 27 -> 22

ATTR_TARGET_ARRY = np.array([ATTR_GENDER_IDX, ATTR_AGE_IDX])
